name: VULNERABLE WORKFLOW

on:
  workflow_dispatch:

permissions: {}

jobs:
  vulnerable:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # 6.0.0
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # 6.0.0
